import type { Metadata } from "next";
import localfont from "next/font/local";
import Script from "next/script";
import "./globals.css";

const arcade_font = localfont({
  src: './resources/fonts/ARCADE_N.ttf'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${arcade_font.className} antialiased`}
      >
        {children}
        <Script src="tetris.js" strategy="afterInteractive" />
      </body>
    </html>
  );
}
